/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIntroText: typeof import('./src/components/AppIntroText.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AppMenuButton: typeof import('./src/components/AppMenuButton.vue')['default']
    BlackList: typeof import('./src/components/CorePages/BlackList.vue')['default']
    BookmarkTip: typeof import('./src/components/ui/BookmarkTip.vue')['default']
    Breadcrumb: typeof import('./src/components/ui/Breadcrumb.vue')['default']
    ChatList: typeof import('./src/components/CorePages/ChatList.vue')['default']
    ChatRoom: typeof import('./src/components/CorePages/ChatRoom.vue')['default']
    ChatS: typeof import('./src/components/phone/ChatS.vue')['default']
    ContactsS: typeof import('./src/components/phone/ContactsS.vue')['default']
    CreatKey: typeof import('./src/components/CorePages/CreatKey.vue')['default']
    CyberpunkScanner: typeof import('./src/components/ui/CyberpunkScanner.vue')['default']
    DiscoverS: typeof import('./src/components/phone/DiscoverS.vue')['default']
    FooterS: typeof import('./src/components/ui/FooterS.vue')['default']
    FriendBj: typeof import('./src/components/CorePages/FriendBj.vue')['default']
    FriendList: typeof import('./src/components/CorePages/FriendList.vue')['default']
    FrostedGlass: typeof import('./src/components/ui/FrostedGlass.vue')['default']
    GameCard: typeof import('./src/components/ui/GameCard.vue')['default']
    IceTag: typeof import('./src/components/ui/IceTag.vue')['default']
    IndexPage: typeof import('./src/components/phone/IndexPage.vue')['default']
    LanguageSwitcher: typeof import('./src/components/tools/LanguageSwitcher.vue')['default']
    LanguageSwitcherPage: typeof import('./src/components/tools/LanguageSwitcherPage.vue')['default']
    Login: typeof import('./src/components/CorePages/Login.vue')['default']
    MeS: typeof import('./src/components/phone/MeS.vue')['default']
    NativeTab: typeof import('./src/components/phone/NativeTab.vue')['default']
    NavBarS: typeof import('./src/components/ui/NavBarS.vue')['default']
    NavBarS1: typeof import('./src/components/ui/NavBarS1.vue')['default']
    ParticleBackground: typeof import('./src/components/ui/ParticleBackground.vue')['default']
    ParticleEffect: typeof import('./src/components/ui/ParticleEffect.vue')['default']
    PonzsColor1: typeof import('./src/components/ui/ponzsColor1.vue')['default']
    QRScanner: typeof import('./src/components/tools/QRScanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkFlow: typeof import('./src/components/ui/TalkFlow.vue')['default']
    ThemeSwitcher: typeof import('./src/components/tools/ThemeSwitcher.vue')['default']
    TypingEffect: typeof import('./src/components/ui/TypingEffect.vue')['default']
    UserCard: typeof import('./src/components/CorePages/UserCard.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
