/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const GunStorageAdapter: typeof import('./composables/GunStorageAdapter')['default']
  const SEA: typeof import('./composables/useGun')['SEA']
  const TalkFlowCore: typeof import('./composables/TalkFlowCore')['default']
  const cleanupNetwork: typeof import('./composables/useNetwork')['cleanupNetwork']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createGun: typeof import('./composables/gun-ionic-adapter')['createGun']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const fetchModels: typeof import('./composables/ollamaService')['fetchModels']
  const generateReply: typeof import('./composables/ollamaService')['generateReply']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getEnabledPeer: typeof import('./composables/useGun')['getEnabledPeer']
  const getGun: typeof import('./composables/useGun')['getGun']
  const getGunSQLiteAdapter: typeof import('./composables/GunStorageAdapter')['getGunSQLiteAdapter']
  const getGunStorageAdapter: typeof import('./composables/GunStorageAdapter')['getGunStorageAdapter']
  const getPeersList: typeof import('./composables/useGun')['getPeersList']
  const getTalkFlowCore: typeof import('./composables/TalkFlowCore')['getTalkFlowCore']
  const gunIonicAdapter: typeof import('./composables/gun-ionic-adapter')['default']
  const h: typeof import('vue')['h']
  const initializeGun: typeof import('./composables/useGun')['initializeGun']
  const initializeRoomTables: typeof import('./composables/useRoomChat')['initializeRoomTables']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const sharedStorage: typeof import('./composables/sharedStorage')['default']
  const showToast: typeof import('./composables/useToast')['showToast']
  const sounds: typeof import('./composables/sounds')['default']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAIAutoReply: typeof import('./composables/useAIAutoReply')['useAIAutoReply']
  const useAIChat: typeof import('./composables/GunOllama')['useAIChat']
  const useAttrs: typeof import('vue')['useAttrs']
  const useChatFlow: typeof import('./composables/TalkFlowCore')['useChatFlow']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useDevChannel: typeof import('./composables/useDevChannel')['default']
  const useDeviceTracking: typeof import('./composables/useDeviceTracking')['default']
  const useFileHandler: typeof import('./composables/useFileHandler')['useFileHandler']
  const useGunSQLiteAdapter: typeof import('./composables/GunStorageAdapter')['useGunSQLiteAdapter']
  const useGunStorageAdapter: typeof import('./composables/GunStorageAdapter')['useGunStorageAdapter']
  const useId: typeof import('vue')['useId']
  const useImageToBase64: typeof import('./composables/useImageToBase64')['useImageToBase64']
  const useLanguage: typeof import('./composables/useLanguage')['default']
  const useLink: typeof import('vue-router')['useLink']
  const useModel: typeof import('vue')['useModel']
  const useMoments: typeof import('./composables/useMoments')['default']
  const useNetwork: typeof import('./composables/useNetwork')['useNetwork']
  const useNetworkStatus: typeof import('./composables/useNetworkStatus')['useNetworkStatus']
  const useNotification: typeof import('./composables/useNotification')['default']
  const useRoomChat: typeof import('./composables/useRoomChat')['useRoomChat']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTheme: typeof import('./composables/useTheme')['useTheme']
  const useToast: typeof import('./composables/useToast')['useToast']
  const useVoiceBar: typeof import('./composables/useVoiceBar')['useVoiceBar']
  const useVoiceCall: typeof import('./composables/useVoiceCall')['useVoiceCall']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { IGunSQLiteAdapter } from './composables/GunStorageAdapter'
  import('./composables/GunStorageAdapter')
  // @ts-ignore
  export type { LocalChatMessage, NetworkChatMessage, Buddy, ReceivedRequest, MessageType, MessageStatus, ChatPreview } from './composables/TalkFlowCore'
  import('./composables/TalkFlowCore')
  // @ts-ignore
  export type { DeviceRecord } from './composables/useDeviceTracking'
  import('./composables/useDeviceTracking')
  // @ts-ignore
  export type { SEAPair, Room, RoomRequest, RoomMessage } from './composables/useRoomChat'
  import('./composables/useRoomChat')
  // @ts-ignore
  export type { CallState } from './composables/useVoiceCall'
  import('./composables/useVoiceCall')
}
